### ISSUE TITLE
Ensure the variable name is not reserved

### ISSUE THREAD

**Issue by suy** [clemenssielaff/breakable_scope#1]
Hi. First, thanks for this. :)  I wanted something like this to experiment in some cases when I had to deal with system APIs in C, and the error recovery was too tricky, and I failed to use smart pointers for it. I did [a simple experiment](https://gitlab.com/suy/once-block) where I focused in trying to get an overview of which implementation would end up with no overhead. But your project is cooler.

Now the issue: seems that identifiers as `__breakable_scope_condition_variable` are [reserved and can't be used in user code](https://stackoverflow.com/a/228797). I don't get an immediate warning about this, but might be worth reviewing.

Thanks!

**Comment by clemenssielaff** [comment]
Hi @suy,

thanks your the comment! It has been a while but I just saw it now ... I think it is fair to say that this repo is not actively under development :wink: 

I updated the file to ensure that the variable name is not reserved (55a49c907663a8c3c3c73e904dd34facbdc67deb).

Cheers!
